# -*- coding: utf-8 -*-
"""da5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnGdkdvz0ZQHn8czryBzePUHBhUkGowh
"""

import streamlit as st
import pandas as pd
import numpy as np


st.set_page_config(
    page_title="Egypt Export Attractiveness Dashboard",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)


st.markdown("""
    <style>
    .main { background-color: #0f1116; color: #ffffff; }
    .stMetric { background-color: #1b1e26; padding: 15px; border-radius: 10px; border: 1px solid #2d3139; }
    div[data-testid="stExpander"] { background-color: #1b1e26; border-radius: 10px; }
    .stTabs [data-baseweb="tab"] { font-size: 16px; font-weight: bold; color: #a3a8b4; }
    .stTabs [data-baseweb="tab"]:hover { color: #00f2fe; }
    .stTabs [aria-selected="true"] { color: #00f2fe !important; border-bottom-color: #00f2fe !important; }
    </style>
""", unsafe_allow_html=True)


@st.cache_data
def load_data():
    df = pd.read_csv('ph5.csv')
    df.columns = df.columns.str.strip()
    return df

df = load_data()


st.title("🌍 Egypt Global Export Attractiveness Monitor")
st.markdown("An intelligent dynamic dashboard designed to analyze and identify promising target markets and export opportunities for Egypt.")
st.markdown("---")


st.sidebar.header("🎛️ Control & Filter Panel")
st.sidebar.markdown("Dynamically filter data based on target market priority status:")


all_priorities = df['Perirtizing'].unique().tolist()
selected_priorities = st.sidebar.multiselect(
    "Select Priority Status:",
    options=all_priorities,
    default=all_priorities
)

filtered_df = df[df['Perirtizing'].isin(selected_priorities)]

col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric(label="📊 Total Target Markets", value=len(filtered_df))
with col2:
    st.metric(label="🔝 Highest Attractiveness Score", value=f"{filtered_df['Total Score'].max()} / 10")
with col3:
    st.metric(label="📦 Average Market Size", value=f"{int(filtered_df['Market Size'].mean()):,}")
with col4:
    st.metric(label="📈 Maximum Available Growth Rate", value=f"{filtered_df['Growth'].max()}%")

st.markdown("<br>", unsafe_allow_html=True)


tab1, tab2, tab3, tab4 = st.tabs([
    "🎯 Q1: Market Evaluation Mechanism",
    "🔢 Q2: Detailed Scores Matrix",
    "🏆 Q3: Top Attractiveness Index",
    "🇪🇬 Q4: Promising Opportunities for Egypt"
])

with tab1:
    st.subheader("📌 Analysis of Raw Factors Influencing Market Evaluation")
    st.markdown("This table displays the core raw metrics (Size, Growth, Logistics, Tariffs) for each country clearly and without complexity:")

    q1_cols = ['Target Market', 'Market Size', 'Growth', 'Logistics', 'Tariffs', 'Perirtizing']
    st.dataframe(
        filtered_df[q1_cols].sort_values(by='Market Size', ascending=False),
        use_container_width=True,
        hide_index=True
    )


with tab2:
    st.subheader("🔢 Labeled Standard Scores for Each Market (Scores Matrix)")
    st.markdown("Here, raw values are transformed into standardized scores (from 1 to 10) to calculate a fair relative weight:")

    q2_cols = ['Target Market', 'Market size score', 'Growth score', 'Logistics score', 'Tariff score', 'Total Score']
    st.dataframe(
        filtered_df[q2_cols].sort_values(by='Total Score', ascending=False),
        use_container_width=True,
        hide_index=True
    )


with tab3:
    st.subheader("🏆 Leading Markets in the Export Attractiveness Index")
    st.markdown("Markets sorted in descending order based on the final **Total Score**:")

    top_indexed = filtered_df[['Target Market', 'Total Score', 'Perirtizing']].sort_values(by='Total Score', ascending=False)

    st.dataframe(
        top_indexed.style.background_gradient(subset=['Total Score'], cmap='viridis'),
        use_container_width=True,
        hide_index=True
    )


with tab4:
    st.subheader("🚀 Strategic Roadmap for Egypt's Key Export Opportunities")

    egypt_hits = filtered_df[filtered_df['Perirtizing'] == 'Priority'].sort_values(by='Total Score', ascending=False)

    if not egypt_hits.empty:
        st.success("💡 Immediate Target Markets (First choice for Egyptian exporters):")
        st.dataframe(
            egypt_hits[['Target Market', 'Total Score', 'Market Size', 'Growth', 'Logistics', 'Tariffs']],
            use_container_width=True,
            hide_index=True
        )
    else:
        st.warning("⚠️ No high-priority markets found with the current Sidebar filters.")

    st.markdown("---")
    st.info("⏳ Promising Long-term Strategic Alternative Opportunities:")
    long_term = filtered_df[filtered_df['Perirtizing'] == 'Long-term Opportunity'].sort_values(by='Total Score', ascending=False)
    st.dataframe(
        long_term[['Target Market', 'Total Score', 'Market Size', 'Growth']],
        use_container_width=True,
        hide_index=True
    )
