# -*- coding: utf-8 -*-
"""da5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnGdkdvz0ZQHn8czryBzePUHBhUkGowh
"""

import streamlit as st
import pandas as pd
import numpy as np


st.set_page_config(
    page_title="Egypt Export Attractiveness Dashboard",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)


st.markdown("""
    <style>
    .main { background-color: #0f1116; color: #ffffff; }
    .stMetric { background-color: #1b1e26; padding: 15px; border-radius: 10px; border: 1px solid #2d3139; }
    div[data-testid="stExpander"] { background-color: #1b1e26; border-radius: 10px; }
    .stTabs [data-baseweb="tab"] { font-size: 16px; font-weight: bold; color: #a3a8b4; }
    .stTabs [data-baseweb="tab"]:hover { color: #00f2fe; }
    .stTabs [aria-selected="true"] { color: #00f2fe !important; border-bottom-color: #00f2fe !important; }
    </style>
""", unsafe_allow_html=True)


@st.cache_data
def load_data():
    df = pd.read_csv('ph5.csv')

    df.columns = df.columns.str.strip()
    return df

df = load_data()


st.title("🌍 Egypt Global Export Attractiveness Monitor")
st.markdown("داشبورد ديناميكي ذكي لتحليل وتحديد الأسواق الواعدة وفرص التصدير المتاحة أمام الدولة المصرية.")
st.markdown("---")


st.sidebar.header("🎛️ لوحة التحكم والفلترة")
st.sidebar.markdown("يمكنك تصفية البيانات ديناميكياً بناءً على فئة أولويات الأسواق المستهدفة:")


all_priorities = df['Perirtizing'].unique().tolist()
selected_priorities = st.sidebar.multiselect(
    "اختر فئة الأولويات (Priority Status):",
    options=all_priorities,
    default=all_priorities
)

filtered_df = df[df['Perirtizing'].isin(selected_priorities)]

col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric(label="📊 إجمالي الأسواق المستهدفة", value=len(filtered_df))
with col2:
    st.metric(label="🔝 أعلى مؤشر جاذبية تم تسجيله", value=f"{filtered_df['Total Score'].max()} / 10")
with col3:
    st.metric(label="📦 متوسط حجم الأسواق (Market Size)", value=f"{int(filtered_df['Market Size'].mean()):,}")
with col4:
    st.metric(label="📈 أعلى معدل نمو متاح", value=f"{filtered_df['Growth'].max()}%")

st.markdown("<br>", unsafe_allow_html=True)


tab1, tab2, tab3, tab4 = st.tabs([
    "🎯 Q1: آلية تقييم الأسواق",
    "🔢 Q2: الدرجات التفصيلية (Scores)",
    "🏆 Q3: الأعلى في مؤشر الجاذبية",
    "🇪🇬 Q4: الفرص الواعدة لمصر"
])

with tab1:
    st.subheader("📌 تحليل العوامل الخام المؤثرة في تقييم الأسواق")
    st.markdown("يعرض هذا الجدول العوامل والمقاييس الأساسية المستهدفة (الحجم، النمو، اللوجستيات، التعرفة الجمركية) لكل دولة بشكل نقي بدون تعقيد:")

    q1_cols = ['Target Market', 'Market Size', 'Growth', 'Logistics', 'Tariffs', 'Perirtizing']
    st.dataframe(
        filtered_df[q1_cols].sort_values(by='Market Size', ascending=False),
        use_container_width=True,
        hide_index=True
    )


with tab2:
    st.subheader("🔢 نقاط التقييم المعيارية لكل سوق (Scores Matrix)")
    st.markdown("هنا يتم تحويل القيم الخام إلى نقاط معيارية من (1 إلى 10) لحساب الوزن النسبي العادل:")

    q2_cols = ['Target Market', 'Market size score', 'Growth score', 'Logistics score', 'Tariff score', 'Total Score']
    st.dataframe(
        filtered_df[q2_cols].sort_values(by='Total Score', ascending=False),
        use_container_width=True,
        hide_index=True
    )


with tab3:
    st.subheader("🏆 الأسواق المتصدرة لمؤشر جاذبية التصدير (Export Attractiveness Index)")
    st.markdown("الأسواق المرتبة تنازلياً بناءً على الـ **Total Score** النهائي:")


    top_indexed = filtered_df[['Target Market', 'Total Score', 'Perirtizing']].sort_values(by='Total Score', ascending=False)

styled_df = top_indexed.style.background_gradient(subset=['Total Score'], cmap='viridis')

st.dataframe(
    styled_df,
    use_container_width=True,
    hide_index=True
)



with tab4:
    st.subheader("🚀 الخريطة الاستراتيجية لأبرز الفرص التصديرية لمصر")


    egypt_hits = filtered_df[filtered_df['Perirtizing'] == 'Priority'].sort_values(by='Total Score', ascending=False)

    if not egypt_hits.empty:
        st.success("💡 الأسواق المستهدفة فوراً (الخيار الأول للمصدر المصري):")
        st.dataframe(
            egypt_hits[['Target Market', 'Total Score', 'Market Size', 'Growth', 'Logistics', 'Tariffs']],
            use_container_width=True,
            hide_index=True
        )
    else:
        st.warning("⚠️ لم يتم تحديد أسواق ذات أولوية قصوى (Priority) في الفلترة الحالية للـ Sidebar.")


    st.markdown("---")
    st.info("⏳ أسواق واعدة على المدى الطويل كبدائل استراتيجية (Long-term Opportunities):")
    long_term = filtered_df[filtered_df['Perirtizing'] == 'Long-term Opportunity'].sort_values(by='Total Score', ascending=False)
    st.dataframe(
        long_term[['Target Market', 'Total Score', 'Market Size', 'Growth']],
        use_container_width=True,
        hide_index=True
    )
